Show error if no data to load

diff --git a/dbload b/dbload
--- a/dbload
+++ b/dbload
@@ -14,6 +14,16 @@ while [ -e ${DB_NAME}.dump.${n} ] ; do
 	last=${n}
 	n=`expr $n + 1`
 done
+
+if [ "${last}" == "-" ] ; then
+	echo ""
+	echo "Sorry, you don't have any data file to load"
+	echo "Could not find ${DB_NAME}.dump.1"
+	echo ""
+	exit 1
+fi
+
+# Display the file
 dumpfile=${DB_NAME}.dump.${last}
 echo ''
 ls -l $dumpfile
