Tidy command, handle non-sequential data files

diff --git a/dump b/dump
--- a/dump
+++ b/dump
@@ -7,14 +7,34 @@
 bin=`dirname $0`
 . $bin/dbenv.sh
 
-# Find a unique dump name
-n=1
-while [ -e ${bin}/${DB_NAME}.dump.${n} ] ; do
-	n=`expr $n + 1`
+#
+#	Find the latest dump file
+#
+last='0'
+for file in ${bin}/${DB_NAME}.dump.* ; do
+	# Ignore files with a non-numeric suffix
+	suffix=`echo ${file} | sed 's/.*\.dump\.\(.*\)$/\1/'`
+	num=`expr ${suffix} + 0 2>/dev/null` # Produces "" if non-numeric
+	[ "$num" != "" ] && [ "$num" -gt ${last} ] && last=$num
 done
-dumpfile=${bin}/${DB_NAME}.dump.${n}
 
-echo "(Password is 'admin')"
-ssh root@${DOCKER_IP} -p ${SSH_PORT} mysqldump --add-drop-table -u root ${bin}/${DB_NAME} > ${dumpfile}
-echo ''
+#
+#	Use the next number
+#
+next=`expr ${last} + 1`
+dumpfile=${bin}/${DB_NAME}.dump.${next}
+
+#
+#	Dump the data
+#
+ssh root@${DOCKER_IP} -p ${SSH_PORT} mysqldump --add-drop-table -u root ${DB_NAME} > ${dumpfile}
+if [ $? != 0 ] ; then
+	rm ${dumpfile}
+	echo ""
+	echo "Error: Dump failed"
+	echo ""
+	exit 1
+fi
+echo ""
 ls -l $dumpfile
+exit 0
